
GMAIL_ADDRESS: "takehiromouri@gmail.com"
GMAIL_PASSWORD: "t22thegoat"
AWS_ACCESS_KEY: "AKIAJVGH6EE7NA3TT23A"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "techrise"

SLACK_API: xoxp-19510056500-19510056516-58812858308-4f915dc512