development:
  adapter: redis
  url: redis://localhost:6379/1

staging:
  adapter: redis
  url: redis://redistogo:c7b2fb013c95b36b67760fa2080eaffe@sculpin.redistogo.com:10413/

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:95c7f6aacec8403674aed08a8790ba45@sculpin.redistogo.com:10414/
